name: Build and deploy JAR app to releases
on:
  push:
    branches:
      - "19.1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup variables
      id: project
      shell: bash
      run: sh ${{ github.action_path }}/setup_variables.sh . 17

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Packaging Jar
      id: packaging-jar
      shell: bash
      run: |
        # COMMAND THAT COMPILES -----
        mvn clean install
        
    - name: Delete existing release and tag
      id: delete-tag-release
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
        tag_name: ${{ steps.project.outputs.version }}
        delete_release: true

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.project.outputs.version }}
        release_name: Release
        body: "automatic release"
        draft: false
        prerelease: true

    - name: Upload Release jar
      id: upload-release-asset-jar
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/KlashItemSys-1.0.jar
        asset_name: KlashItemSys-1.0.jar
        asset_content_type: application/java-archive
